disabled_rules: # rule identifiers to exclude from running
  #- trailing_newline
  #- opening_brace
  - empty_count
  #- comma
  #- colon
  #- cyclomatic_complexity
  - force_cast
  - type_name
  #- trailing_semicolon
  - force_try
  - function_body_length
  - function_parameter_count
  - nesting
  - variable_name
  #- operator_whitespace
  - control_statement
  - legacy_constant
  #- line_length
  #- return_arrow_whitespace
  #- trailing_whitespace
  - closing_brace
  #- statement_position
  - type_body_length
  - todo
  - legacy_constructor
  - valid_docs
  - missing_docs
  - file_length
  #- leading_whitespace
  - implicit_getter
  - redundant_void_return
opt_in_rules: # some rules are only opt-in
  #- empty_count
  #- missing_docs
  # Find all the available rules by running:
  # swiftlint rules
whitelist_rules:
included:
  - CleanItunesCore/Classes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  - 510
  - 800
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
function_parameter_count:
  warning: 3
  error: 6
cyclomatic_complexity:
  warning: 10
  error: 20
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
